import { createApp } from "vue";
import App from "./App.vue";
import store from "./store/index";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAlienMonster,
  faArrowDown,
  faArrowUp,
  faAtomAlt,
  faAxeBattle,
  faBiohazard,
  faBomb,
  faBook,
  faBookmark,
  faBowArrow,
  faCameraMovie,
  faCheck,
  faChess,
  faChessBishop,
  faChessKnight,
  faCoffee,
  faCompactDisc,
  faCowbell,
  faDatabase,
  faDesktop,
  faDice,
  faDiceD20,
  faDizzy,
  faDungeon,
  faFilm,
  faGameConsoleHandheld,
  faGamepad,
  faGamepadAlt,
  faGhost,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGrimace,
  faGrin,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGuitar,
  faGuitarElectric,
  faHatWizard,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeadVr,
  faHeart,
  faJoystick,
  faLaptop,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faMapMarked,
  faMeh,
  faMehRollingEyes,
  faMeteor,
  faMicrophone,
  faMouse,
  faMusic,
  faMusicAlt,
  faPaw,
  faPianoKeyboard,
  faPopcorn,
  faQuestion,
  faRobot,
  faRocket,
  faRoute,
  faSadCry,
  faSaxophone,
  faScroll,
  faSmileBeam,
  faSmileWink,
  faStaff,
  faStar,
  faStarfighter,
  faStarfighterAlt,
  faStarship,
  faStarshipFreighter,
  faSurprise,
  faSword,
  faTrophy,
  faTv,
  faUserHeadset,
  faViolin,
  faWebcam,
  faTimesCircle
} from "@fortawesome/pro-solid-svg-icons";
import {
  faArrowCircleUp,
  faCloudDownloadAlt,
  faGem,
  faIcons,
  faImage,
  faImages
} from "@fortawesome/pro-duotone-svg-icons";
import {
  faDiscord,
  faPlaystation,
  faVuejs,
  faXbox,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
library.add(
  faAlienMonster,
  faArrowCircleUp,
  faArrowDown,
  faArrowUp,
  faAtomAlt,
  faAxeBattle,
  faBiohazard,
  faBomb,
  faBook,
  faBookmark,
  faBowArrow,
  faCameraMovie,
  faCheck,
  faChess,
  faChessBishop,
  faChessKnight,
  faCloudDownloadAlt,
  faCoffee,
  faCompactDisc,
  faCowbell,
  faDatabase,
  faDesktop,
  faDice,
  faDiceD20,
  faDiscord,
  faDizzy,
  faDungeon,
  faFilm,
  faGameConsoleHandheld,
  faGamepad,
  faGamepadAlt,
  faGem,
  faGhost,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGrimace,
  faGrin,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGuitar,
  faGuitarElectric,
  faHatWizard,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeadVr,
  faHeart,
  faIcons,
  faImage,
  faImages,
  faJoystick,
  faLaptop,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faMapMarked,
  faMeh,
  faMehRollingEyes,
  faMeteor,
  faMicrophone,
  faMouse,
  faMusic,
  faMusicAlt,
  faPaw,
  faPianoKeyboard,
  faPlaystation,
  faPopcorn,
  faQuestion,
  faRobot,
  faRocket,
  faRoute,
  faSadCry,
  faSaxophone,
  faScroll,
  faSmileBeam,
  faSmileWink,
  faStaff,
  faStar,
  faStarfighter,
  faStarfighterAlt,
  faStarship,
  faStarshipFreighter,
  faSurprise,
  faSword,
  faTimesCircle,
  faTrophy,
  faTv,
  faUserHeadset,
  faViolin,
  faVuejs,
  faWebcam,
  faXbox
);

// Base Components
import BaseHeader from "./components/ui/BaseHeader.vue";
import BaseCheckbox from "./components/ui/BaseCheckbox.vue";
import BaseRadioButton from "./components/ui/BaseRadioButton.vue";
import BaseInput from "./components/ui/BaseInput.vue";
import BaseImageUpload from "./components/ui/BaseImageUpload.vue";
import BaseAchievement from "./components/ui/BaseAchievement.vue";
import BaseAchievementImage from "./components/ui/BaseAchievementImage.vue";
import BaseAchievementHeader from "./components/ui/BaseAchievementHeader.vue";
import BaseAchievementText from "./components/ui/BaseAchievementText.vue";

const app = createApp(App);
app.component("font-awesome-icon", FontAwesomeIcon);
app.component("base-image-upload", BaseImageUpload);
app.component("base-header", BaseHeader);
app.component("base-checkbox", BaseCheckbox);
app.component("base-radio-button", BaseRadioButton);
app.component("base-input", BaseInput);
app.component("base-achievement", BaseAchievement);
app.component("base-achievement-image", BaseAchievementImage);
app.component("base-achievement-header", BaseAchievementHeader);
app.component("base-achievement-text", BaseAchievementText);

app.use(store);

app.mount("#app");
