import { createApp } from "vue";
import App from "./App.vue";
import store from "./store/index";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAlienMonster,
  faAppleAlt,
  faArrowDown,
  faArrowUp,
  faAtomAlt,
  faAxeBattle,
  faBacon,
  faBaseball,
  faBiking,
  faBiohazard,
  faBomb,
  faBook,
  faBookmark,
  faBowArrow,
  faBowlingBall,
  faBoxingGlove,
  faBurgerSoda,
  faCameraMovie,
  faCandyCane,
  faCheck,
  faCheeseburger,
  faCheeseSwiss,
  faChess,
  faChessBishop,
  faChessKnight,
  faCocktail,
  faCoffee,
  faCoffeeTogo,
  faCompactDisc,
  faCowbell,
  faCricket,
  faCurling,
  faDatabase,
  faDesktop,
  faDice,
  faDiceD20,
  faDizzy,
  faDumbbell,
  faDungeon,
  faEggFried,
  faFieldHockey,
  faFilm,
  faFish,
  faFootballBall,
  faFootballHelmet,
  faFutbol,
  faGameConsoleHandheld,
  faGamepad,
  faGamepadAlt,
  faGhost,
  faGlassWhiskeyRocks,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGolfBall,
  faGrimace,
  faGrin,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGuitar,
  faGuitarElectric,
  faHatWizard,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeadVr,
  faHeart,
  faHockeySticks,
  faJoystick,
  faLaptop,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLemon,
  faMapMarked,
  faMeh,
  faMehRollingEyes,
  faMeteor,
  faMicrophone,
  faMouse,
  faMusic,
  faMusicAlt,
  faPaw,
  faPennant,
  faPepperHot,
  faPianoKeyboard,
  faPie,
  faPizza,
  faPizzaSlice,
  faPopcorn,
  faPumpkin,
  faQuestion,
  faQuidditch,
  faRacquet,
  faRobot,
  faRocket,
  faRoute,
  faRunning,
  faSadCry,
  faSalad,
  faSandwich,
  faSausage,
  faSaxophone,
  faScroll,
  faShuttlecock,
  faSkating,
  faSkiing,
  faSmileBeam,
  faSmileWink,
  faSnowboarding,
  faSoup,
  faStaff,
  faStar,
  faStarfighter,
  faStarfighterAlt,
  faStarship,
  faStarshipFreighter,
  faSurprise,
  faSwimmer,
  faSword,
  faTableTennis,
  faTaco,
  faTennisBall,
  faTimesCircle,
  faTrophy,
  faTurkey,
  faTv,
  faUserHeadset,
  faUtensilsAlt,
  faViolin,
  faVolleyballBall,
  faWalking,faGlassCheers,
  faWebcam,
  faWineGlassAlt,
} from "@fortawesome/pro-solid-svg-icons";
import {
  faArrowCircleUp,
  faCloudDownloadAlt,
  faGem,
  faIcons,
  faImage,
  faImages,
  faPortalEnter,
  faPortalExit
} from "@fortawesome/pro-duotone-svg-icons";
import {
  faDiscord,
  faPlaystation,
  faSteam,
  faVuejs,
  faXbox,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
library.add(




  faAlienMonster,
  faAppleAlt,
  faArrowCircleUp,
  faArrowDown,
  faArrowUp,
  faAtomAlt,
  faAxeBattle,
  faBacon,
  faBaseball,
  faBiking,
  faBiohazard,
  faBomb,
  faBook,
  faBookmark,
  faBowArrow,
  faBowlingBall,
  faBoxingGlove,
  faBurgerSoda,
  faCameraMovie,
  faCandyCane,
  faCheck,
  faCheeseburger,
  faCheeseSwiss,
  faChess,
  faChessBishop,
  faChessKnight,
  faCloudDownloadAlt,
  faCocktail,
  faCoffee,
  faCoffeeTogo,
  faCompactDisc,
  faCowbell,
  faCricket,
  faCurling,
  faDatabase,
  faDesktop,
  faDice,
  faDiceD20,
  faDiscord,
  faDizzy,
  faDumbbell,
  faDungeon,
  faEggFried,
  faFieldHockey,
  faFilm,
  faFish,
  faFootballBall,
  faFootballHelmet,
  faFutbol,
  faGameConsoleHandheld,
  faGamepad,
  faGamepadAlt,
  faGem,
  faGhost,
  faGlassCheers,
  faGlassWhiskeyRocks,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGolfBall,
  faGrimace,
  faGrin,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGuitar,
  faGuitarElectric,
  faHatWizard,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeadVr,
  faHeart,
  faHockeySticks,
  faIcons,
  faImage,
  faImages,
  faJoystick,
  faLaptop,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLemon,
  faMapMarked,
  faMeh,
  faMehRollingEyes,
  faMeteor,
  faMicrophone,
  faMouse,
  faMusic,
  faMusicAlt,
  faPaw,
  faPennant,
  faPepperHot,
  faPianoKeyboard,
  faPie,
  faPizza,
  faPizzaSlice,
  faPlaystation,
  faPopcorn,
  faPumpkin,
  faQuestion,
  faQuidditch,
  faRacquet,
  faRobot,
  faRocket,
  faRoute,
  faRunning,
  faSadCry,
  faSalad,
  faSandwich,
  faSausage,
  faSaxophone,
  faScroll,
  faShuttlecock,
  faSkating,
  faSkiing,
  faSmileBeam,
  faSmileWink,
  faSnowboarding,
  faSoup,
  faStaff,
  faStar,
  faStarfighter,
  faStarfighterAlt,
  faStarship,
  faStarshipFreighter,
  faSurprise,
  faSwimmer,
  faSword,
  faSteam,
  faTableTennis,
  faTaco,
  faTennisBall,
  faTimesCircle,
  faTrophy,
  faTurkey,
  faTv,
  faUserHeadset,
  faUtensilsAlt,
  faViolin,
  faVolleyballBall,
  faVuejs,
  faWalking,
  faWebcam,
  faWineGlassAlt,
  faXbox,
  faPortalEnter,
  faPortalExit
);

// Base Components
import BaseHeader from "./components/ui/BaseHeader.vue";
import BaseCheckbox from "./components/ui/BaseCheckbox.vue";
import BaseRadioButton from "./components/ui/BaseRadioButton.vue";
import BaseInput from "./components/ui/BaseInput.vue";
import BaseImageUpload from "./components/ui/BaseImageUpload.vue";
import BaseAchievement from "./components/ui/BaseAchievement.vue";
import BaseAchievementImage from "./components/ui/BaseAchievementImage.vue";
import BaseAchievementHeader from "./components/ui/BaseAchievementHeader.vue";
import BaseAchievementText from "./components/ui/BaseAchievementText.vue";

const app = createApp(App);
app.component("font-awesome-icon", FontAwesomeIcon);
app.component("base-image-upload", BaseImageUpload);
app.component("base-header", BaseHeader);
app.component("base-checkbox", BaseCheckbox);
app.component("base-radio-button", BaseRadioButton);
app.component("base-input", BaseInput);
app.component("base-achievement", BaseAchievement);
app.component("base-achievement-image", BaseAchievementImage);
app.component("base-achievement-header", BaseAchievementHeader);
app.component("base-achievement-text", BaseAchievementText);

app.use(store);

app.mount("#app");
